### ISSUE TITLE
dataset generation issue

### ISSUE THREAD

**Issue by rubliw999** [majianjia/nnom#185]
Hi, 
Running into this error while generating the dataset:
.........
Reading noisy and clean speech files...
generating clean speech MFCC...
generating noisy speech MFCC...
generating noisy MFCC...
Processing training data
Traceback (most recent call last):
  File "gen_dataset.py", line 349, in <module>
    np.savez("dataset.npz", clnsp_mfcc=clnsp_mfcc, noisy_mfcc=noisy_mfcc, noise_mfcc=noise_mfcc, vad=voice_active, gains=gains_array)
  File "<__array_function__ internals>", line 200, in savez
  File "dnnenv\lib\site-packages\numpy\lib\npyio.py", line 615, in savez
    _savez(file, args, kwds, False)
  File "dnnenv\lib\site-packages\numpy\lib\npyio.py", line 716, in _savez
    val = np.asanyarray(val)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (876,) + inhomogeneous part.

Any clue what is happening?
Thanks!

**Comment by rubliw999** [comment]
The array dimensions are fine and I think this is because gains_array is of type float64 and voice_active array is of type int32 and the others are float32. Any harm in making them all float32?

**Comment by rubliw999** [comment]
The issue is that the feature size is different for one (could be more) of the files probably because of its size. ie
clnsp_mfcc[2].shape = (3930,20)
clnsp_mfcc[3].shape = (3851,20)
Is there an issue if we force the size of the input data if smaller by appending zeros?
